name: CI

on: [push]

jobs:
  tests:
    name: Unit-Tests
    runs-on: macos-10.15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Force Xcode 12.2
        run: sudo xcode-select -switch /Applications/Xcode_12.2.app
      - name: fastlane ios tests
        run: fastlane ios tests
  compatibility:
    name: Compatibility-Tests
    runs-on: macos-10.15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Force Xcode 12.2
        run: sudo xcode-select -switch /Applications/Xcode_12.2.app
      - name: fastlane ios compatibilityTests
        run: fastlane ios compatibilityTests
